### ISSUE TITLE
Not working on 1.16.5

### ISSUE THREAD

**Issue by Teals53** [InventivetalentDev/SaturationPreview#13]
[04:06:07 INFO]: [ReflectionHelper] I am loaded from package org.inventivetalent.saturationpreview.reflection.minecraft
[04:06:07 WARN]: [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_16_R3'/'v1_16_R3.'
[04:06:07 INFO]: [ReflectionHelper] Generating dynamic constant...
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.inventivetalent.saturationpreview.reflection.util.AccessUtil (file:/C:/Users/cerez8/Desktop/tealsvival/plugins/SaturationPreview_v1.3.1.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.inventivetalent.saturationpreview.reflection.util.AccessUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[04:06:07 ERROR]: Could not load 'plugins\SaturationPreview_v1.3.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: sun/reflect/ConstructorAccessor
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-631]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-631]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-631]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-631]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-631]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-631]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-631]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: sun/reflect/ConstructorAccessor
        at org.inventivetalent.saturationpreview.reflection.minecraft.Minecraft.newEnumInstance(Minecraft.java:239) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:204) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:34) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:15) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:16) ~[?:?]
        at org.inventivetalent.saturationpreview.SaturationPreview.<clinit>(SaturationPreview.java:36) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-631]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-631]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: sun.reflect.ConstructorAccessor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-631]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-631]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.minecraft.Minecraft.newEnumInstance(Minecraft.java:239) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:204) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:34) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:15) ~[?:?]
        at org.inventivetalent.saturationpreview.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:16) ~[?:?]
        at org.inventivetalent.saturationpreview.SaturationPreview.<clinit>(SaturationPreview.java:36) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-631]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-631]
        ... 7 more
